//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroMusic.Entity.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedSong
    {
        public int Id { get; set; }
        public string SongName { get; set; }
        public string Email { get; set; }
    }
}
