//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroMusic.Entity.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int SongId { get; set; }
        public string SongName { get; set; }
        public string Artist { get; set; }
        public string Year { get; set; }
        public string AlbumName { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
    }
}
